name: Update Google Fonts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 1 * *'

permissions:
  contents: read

env:
  GIT_AUTHOR_EMAIL: 94923726+googleforcreators-bot@users.noreply.github.com
  GIT_AUTHOR_NAME: googleforcreators-bot
  GIT_COMMITTER_EMAIL: 94923726+googleforcreators-bot@users.noreply.github.com
  GIT_COMMITTER_NAME: googleforcreators-bot

jobs:
  update-fonts:
    name: Update Google Fonts
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          token: ${{ secrets.GOOGLEFORCREATORS_BOT_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc

      - name: Install dependencies
        run: bun install
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Update list of Google Fonts
        env:
          GOOGLE_FONTS_API_KEY: ${{ secrets.GOOGLE_FONTS_API_KEY }}
        run: bun run workflow:fonts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.GOOGLEFORCREATORS_BOT_TOKEN }}
          commit-message: Update list of Google Fonts
          title: Update list of Google Fonts
          body: Fetched the currently available fonts on Google Fonts to update them in the project.
          branch: update/google-fonts
          labels: Dependencies
