name: Update browserslist db

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 1 * *'

permissions:
  contents: read

env:
  GIT_AUTHOR_EMAIL: 94923726+googleforcreators-bot@users.noreply.github.com
  GIT_AUTHOR_NAME: googleforcreators-bot
  GIT_COMMITTER_EMAIL: 94923726+googleforcreators-bot@users.noreply.github.com
  GIT_COMMITTER_NAME: googleforcreators-bot

jobs:
  update-browserslist-db:
    name: Update browserslist db
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          token: ${{ secrets.GOOGLEFORCREATORS_BOT_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc

      - name: Update db
        run: bunx browserslist@latest --update-db

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@a4f52f8033a6168103c2538976c07b467e8163bc
        with:
          token: ${{ secrets.GOOGLEFORCREATORS_BOT_TOKEN }}
          commit-message: Update browserslist db
          title: Update browserslist db
          body: Updates `caniuse-lite` to use the latest browser’s versions and statistics.
          branch: update/browserslist-db
          labels: Dependencies
